import './globals.css'
import type { Metadata } from 'next'
import { Inter,Arvo } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })
const arvo = Arvo({weight:["400","700"],style:["normal","italic"], subsets:["latin"] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={arvo.className}>{children}</body>
    </html>
  )
}
